spring:
  application:
    name: Audsat-Insurance
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:insurancedb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    locations:
      - classpath:db/migration
    enabled: true


springdoc:
  api-docs:
    enabled: true
  packages-to-scan: com.audsat.insurance.controller